### ISSUE TITLE
Uncaught TypeError: Cannot read property 'member' of undefined

### ISSUE THREAD

**Issue by ghost** [anotherfrog/java-class-complete#1]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.6.0
**System**: Microsoft Windows 10 Pro
**Thrown From**: [java-class-complete](https://github.com/anotherfrog/java-class-complete) package, v0.0.2
### Stack Trace

Uncaught TypeError: Cannot read property 'member' of undefined

```
At /C:/Users/Alex/.atom/packages/java-class-complete/lib/java-complete.coffee:50

TypeError: Cannot read property 'member' of undefined
    at JavaTemplate.generateMethod (file:///C:/Users/Alex/.atom/packages/java-class-complete/lib/java-complete.coffee:40:29)
    at JavaTemplate.generateClass (file:///C:/Users/Alex/.atom/packages/java-class-complete/lib/java-complete.coffee:13:28)
    at CompleteHandler.complete (file:///C:/Users/Alex/.atom/packages/class-complete/lib/complete-handler.coffee:25:35)
    at Complete.complete (file:///C:/Users/Alex/.atom/packages/class-complete/lib/class-complete.coffee:39:20)
    at atom-workspace.atom.commands.add.class-complete:complete (file:///C:/Users/Alex/.atom/packages/class-complete/lib/class-complete.coffee:48:35)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Alex\AppData\Local\atom\app-1.6.0\resources\app.asar\src\command-registry.js:260:29)
    at C:\Users\Alex\AppData\Local\atom\app-1.6.0\resources\app.asar\src\command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\Alex\AppData\Local\atom\app-1.6.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:570:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\Alex\AppData\Local\atom\app-1.6.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:378:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (C:\Users\Alex\AppData\Local\atom\app-1.6.0\resources\app.asar\src\window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (C:\Users\Alex\AppData\Local\atom\app-1.6.0\resources\app.asar\src\window-event-handler.js:3:61)
```
### Commands

```
  5x -0:05.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:03.7.0 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -0:03.3.0 class-complete:complete (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
class-complete, v6.2.2
java-class-complete, v0.0.2

# Dev
No dev packages
```

**Comment by noahbki** [comment]
In progress

**Comment by noahbki** [comment]
Fixed.
